version: '3.8'
services:
  nginx:
    build:
      context: .
    ports:
      - '3000:80'
    volumes:
      - ../../Font-End/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

    # docker compose -p tuanbui-nginx up -d